const fs=require('fs');const assert=require('assert');const path=require('path');
const html=fs.readFileSync(path.resolve(__dirname,'..','index.html'),'utf8');
const career=fs.readFileSync(path.resolve(__dirname,'..','backend','routes','career.js'),'utf8');
const finance=fs.readFileSync(path.resolve(__dirname,'..','backend','routes','finance.js'),'utf8');
['未来支持方案','不预测孩子结局','不要依据诊断标签预设职业','不是法律意见','category: type','target_date: deadline',"progress: status === 'completed' ? 100 : 0",'补贴信息核验','未按您的地区核验','description: note'].forEach(marker=>assert(html.includes(marker),'生涯/财务前端缺少: '+marker));
["router.param('childId'","SELECT id FROM children WHERE id = ? AND user_id = ?",'req.body.title === undefined','目标不存在'].forEach(marker=>assert(career.includes(marker),'生涯接口缺少: '+marker));
["router.param('childId'",'FINANCE_CATEGORIES','Number.isFinite(amount)','verified: false','示例信息，未按地区','正式审核和反馈服务尚未接入'].forEach(marker=>assert(finance.includes(marker),'财务接口缺少: '+marker));
assert(!html.includes('建议重点培养数字技能和编程能力'),'不得按诊断标签预设职业');
assert(!finance.includes('会在24小时内审核'),'未接审核服务不得承诺时限');
console.log('生涯与财务回归通过：去预测和刻板印象、字段契约、儿童所有权、政策核验边界与金额校验齐全。');